services:
  app:
    image: code-portfolio-type
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
      args:
          - REACT_APP_SERVICE_ID=${REACT_APP_SERVICE_ID}
          - REACT_APP_TEMPLATE_ID=${REACT_APP_TEMPLATE_ID}
          - REACT_APP_User_ID=${REACT_APP_User_ID}
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: code-portfolio-type # This will name the container hello-front-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-for-code-portfolio-type
    depends_on:
      - app # wait for the frontend container to be started
